#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/3043cf77-3b19-4f99-b247-fcd202a2dd05 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudLight luz_quarto_direita;
  CloudLight luz_quarto_esquerda;
  CloudLight luz_quarto_tras;
  CloudLight luz_sala;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}

/*
  Since LuzSala1 is READ_WRITE variable, onLuzSala1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLuzSala1Change()  {
  // Add your code here to act upon LuzSala1 change
}

/*
  Since LuzSala2 is READ_WRITE variable, onLuzSala2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLuzSala2Change()  {
  // Add your code here to act upon LuzSala2 change
}

/*  
  Since LuzQuartoEsquerda is READ_WRITE variable, onLuzQuartoEsquerdaChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLuzQuartoEsquerdaChange()  {
  // Add your code here to act upon LuzQuartoEsquerda change
}

/*
  Since LuzQuartoDireita is READ_WRITE variable, onLuzQuartoDireitaChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLuzQuartoDireitaChange()  {
  // Add your code here to act upon LuzQuartoDireita change
}


/*
  Since LuzQuartoTras is READ_WRITE variable, onLuzQuartoTrasChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLuzQuartoTrasChange()  {
  // Add your code here to act upon LuzQuartoTras change
}


/*
  Since LuzSala is READ_WRITE variable, onLuzSalaChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLuzSalaChange()  {
  // Add your code here to act upon LuzSala change
}