// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "e2a3b9b8-8b13-4436-bed9-eaa9c98ffe73";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onLuzGaragemChange();
void onLuzQuartoDireitaChange();
void onLuzQuartoEsquerdaChange();
void onLuzQuartoTrasChange();
void onLuzSalaChange();

CloudSwitch luz_garagem;
CloudSwitch luz_quarto_direita;
CloudSwitch luz_quarto_esquerda;
CloudSwitch luz_quarto_tras;
CloudSwitch luz_sala;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(luz_garagem, READWRITE, 1 * SECONDS, onLuzGaragemChange);
  ArduinoCloud.addProperty(luz_quarto_direita, READWRITE, 1 * SECONDS, onLuzQuartoDireitaChange);
  ArduinoCloud.addProperty(luz_quarto_esquerda, READWRITE, 1 * SECONDS, onLuzQuartoEsquerdaChange);
  ArduinoCloud.addProperty(luz_quarto_tras, READWRITE, 1 * SECONDS, onLuzQuartoTrasChange);
  ArduinoCloud.addProperty(luz_sala, READWRITE, 1 * SECONDS, onLuzSalaChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
